### PR TITLE
Update opentherm.cpp

### PR DESCRIPTION
**Pull request by JWGracht**
Add support for Arduino Leonardo

### CODE REVIEW

**Comment by jpraus** [comment]
Thank you for your contribution!
I am going to get Leonard board ASAP to test your changes and merge it afterwards.

**Comment by Nightenom** [comment]
I can confirm using this edit works for leonardo board (tested 40 different messages over 3 mins)

**Comment by jpraus** [comment]
@Nightenom there is a conflict right now, can you please resolve it? I will then merge it into master and release it.

**Comment by JWGracht** [comment]
Hi Jiri,

That is because you merged the pull request from 27th of december before mine from 5th of december.

I expect I have to create a new pull request now based on your current master and implement the update again? since my part is overwritten now.

Let me know if there are maybe also other solutions, because this is my first pull request I ever did on Github :)

Regards

**Comment by Nightenom** [comment]
@JWGracht you can resolve conflicts either here or using your github client (like gitkraken/github windows/...)
<https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/resolving-a-merge-conflict-on-github>

**Comment by JWGracht** [comment]
Ok. I have copied back to my file and added the new part from commit b91ff3. I think this solves the issue. But I am not able to test this for the Arduino Uno Wifi Rev2 and Arduino Nano boards from commit b91ff3

**Comment by JWGracht** [comment]
Did I do the update correct and is it ok now? Or should I still do something before it can be merged to the library?

**Comment by jpraus** [comment]
Yeah! Thank you! It's in!
Thank you very much for contributing!

**Pull request merged**
